lua require("core.lazy")

" This is the Neovim configuration of Ivar Gaitan <ivar.gaitan@gmail.com>
call plug#begin()




"Plug 'nathanaelkane/vim-indent-guides'
"Plug 'vim-scripts/restore_view.vim'

"Plug 'mhinz/vim-signify'

" Text selection
Plug 'gcmt/wildfire.vim'
Plug 'terryma/vim-expand-region'

" General Programming
Plug 'tpope/vim-fugitive'
Plug 'junegunn/gv.vim'

Plug 'mattn/webapi-vim'
Plug 'mattn/gist-vim'

"Plug 'davidhalter/jedi-vim'
Plug 'ervandew/supertab'

" Go
" Plug 'fatih/vim-go'

" Rust
Plug 'rust-lang/rust.vim'

" Julia
Plug 'JuliaLang/julia-vim'

" React stuff
Plug 'pangloss/vim-javascript'
Plug 'mxw/vim-jsx'


" API Blueprint
Plug 'kylef/apiblueprint.vim'

Plug 'stephpy/vim-yaml'

call plug#end()


""""""""""""""""""""""""""""
"" Settings

" colorscheme jellybeans

" Use system clipboard
set clipboard+=unnamedplus

set undofile                                   " So is persistent undo ...
set cursorline                                 " Highlight current line
set number                                     " Line numbers on
set winminheight=0                             " Windows can be 0 line high
set ignorecase                                 " Case insensitive search
set smartcase                                  " Case sensitive when uc present
set wildmode=list:longest,full                 " Command mode <Tab> completion, list matches, then longest common part, then all.
set whichwrap=b,s,h,l,<,>,[,]                  " Backspace and cursor keys wrap too
set scrolloff=3                                " Minimum lines to keep above and below cursor
set list                                       " Display whitespaces
set shiftwidth=4                               " Use indents of 4 spaces
set tabstop=4                                  " An indentation every four columns
set softtabstop=4                              " Let backspace delete indent
set expandtab                                  " Tabs are spaces, not tabs
set nojoinspaces                               " Prevents inserting two spaces after punctuation on a join (J)
set splitright                                 " Puts new vsplit windows to the right of the current
set splitbelow                                 " Puts new split windows to the bottom of the current
set hidden                                     " Allow buffer switching without saving

"set nofoldenable                               " Disable auto fold code
"set wrap                                       " Do not wrap long lines
"set shortmess+=filmnrxoOt                      " Abbrev. of messages (avoids 'hit enter')
"set virtualedit=onemore                        " Allow for cursor beyond last character
"set iskeyword-=.                               " '.' is an end of word designator
"set iskeyword-=#                               " '#' is an end of word designator
"set iskeyword-=-                               " '-' is an end of word designator
"set showmatch                                  " Show matching brackets/parenthesis
"set scrolljump=5                               " Lines to scroll when cursor leaves screen
"set guioptions-=T                              " Remove the toolbar
"set guioptions-=L                              " Remove scrollbars
"set guioptions-=r


"" Autocommands

" Write buffer when losing focus
" autocmd BufLeave,FocusLost * silent! wall

" Strip trailing whitespace when writing buffer
" FileType matlab,markdown,c,cpp,java,go,javascript,python,rust,xml,yml
" autocmd FileType matlab,markdown,c,cpp,java,go,javascript,javascipt.jsx,rust,xml,yml autocmd BufWritePre <buffer> call StripTrailingWhitespace()

" Always switch to the current file directory
" autocmd BufEnter * if bufname("") !~ "^\[A-Za-z0-9\]*://" | lcd %:p:h | endif

" Instead of reverting the cursor to the last position in the buffer, we
" set it to the first line when editing a git commit message
" autocmd FileType gitcommit au! BufEnter COMMIT_EDITMSG call setpos('.', [0, 1, 1, 0])

" Javascript and Java files use indentation of 2
" autocmd FileType javascript,java,json setlocal shiftwidth=2 tabstop=2

" Restore cursor to file position in previous editing session
augroup resCur
    autocmd!
    autocmd BufWinEnter * call ResCur()
augroup END

augroup BWCCreateDir
    autocmd!
    autocmd BufWritePre * :call s:MkNonExDir(expand('<afile>'), +expand('<abuf>'))
augroup END


"" Mappings

" Leader
let mapleader = ','
let maplocalleader = '_'

nmap ge :Extradite<cr>

" Escape
imap jj <esc><esc>
imap jk <esc><esc>

" Close current buffer without closing window
nnoremap <C-W><C-W> :bd<CR>

" Shortcut for opening file
map <leader>ew :e 


" Normal buffer movements
nnoremap <C-H> <C-W><Left>
nnoremap <C-L> <C-W><Right>
nnoremap <C-J> <C-W><Down>
nnoremap <C-K> <C-W><Up>


" Command buffer movements
cnoremap <C-H> <Left>
cnoremap <C-L> <Right>
cnoremap <C-A> <Home>
cnoremap <C-D> <Del>

" Input mode movements
inoremap <C-H> <Left>
inoremap <C-L> <Right>
inoremap <C-A> <Home>
inoremap <C-D> <Del>

" Shortcuts to quickly exit and reload .vimrc
nmap <leader>av :vsplit $MYVIMRC<cr>
nnoremap <leader>sv :source $MYVIMRC<cr>

" No shift when doing ex commands
nnoremap ; :

" Swedish keyboard convenience
nnoremap ö :
nnoremap - /

" Wrapped lines goes down/up to next row, rather than next line in file.
noremap j gj
noremap k gk

" Yank from the cursor to the end of the line, to be consistent with C and D.
nnoremap Y y$

" Toggle search element highlight
nmap <silent> <leader>/ :set invhlsearch<CR>

" Find merge conflict markers
map <leader>fc /\v^[<\|=>]{7}( .*\|$)<CR>

" Visual shifting (does not exit Visual mode)
vnoremap < <gv
vnoremap > >gv

" Allow using the repeat operator with a visual selection (!)
" http://stackoverflow.com/a/8064607/127816
vnoremap . :normal .<cr>

" Adjust viewports to the same size
map <Leader>= <C-w>=

" Easier horizontal scrolling
map zl zL
map zh zH


"" Functions
"
" Create non-existing directory on save
function! s:MkNonExDir(file, buf)
    if empty(getbufvar(a:buf, '&buftype')) && a:file!~#'\v^\w+\:\/'
        let dir=fnamemodify(a:file, ':h')
        if !isdirectory(dir)
            call mkdir(dir, 'p')
        endif
    endif
endfunction

" Restore cursor to file position in previous editing session
function! ResCur()
    if line("'\"") <= line("$")
        normal! g`"
        return 1
    endif
endfunction

" Strip whitespace
function! StripTrailingWhitespace()
	" Preparation: save last search, and cursor position.
	let _s=@/
	let l = line(".")
	let c = col(".")
	" do the business:
	%s/\s\+$//e
	" clean up: restore previous search history, and cursor position
	let @/=_s
	call cursor(l, c)
endfunction


" matchit
let b:match_ignorecase = 1


"""""""""""""""""""""""""""""
"" Plugin stuff


" jedi-vim plugin stuff
"let g:jedi#completions_command = "<C-s>"

" navigate location list 
noremap <C-n> :lne<CR>
noremap <C-m> :lp<CR>


set statusline+=%#warningmsg#
set statusline+=%*

" vim-autoclose
let g:autoclose_vim_commentmode = 1


" NERDTree
" map <C-e> :NERDTreeToggle<CR>
" map <leader>e :NERDTreeFind<CR>
" nmap <leader>nt :NERDTreeFind<CR>

" Keep NERDTree open after opening a file

let NERDShutUp=1
let NERDTreeShowBookmarks=1
let NERDTreeIgnore=['\.py[cd]$', '\~$', '\.swo$', '\.swp$', '^\.git$', '^\.hg$', '^\.svn$', '\.bzr$']
let NERDTreeChDirMode=0
let NERDTreeMouseMode=2
let NERDTreeShowHidden=1
let NERDTreeKeepTreeInNewTab=1

" This is to solve a nerd-fonts rendering problem
" autocmd FileType nerdtree setlocal nolist


" Ctags
set tags=./tags;/,~/.vimtags
" Make tags placed in .git/tags file available in all levels of a repository
let gitroot = substitute(system('git rev-parse --show-toplevel'), '[\n\r]', '', 'g')
if gitroot != ''
	let &tags = &tags . ',' . gitroot . '/.git/tags'
endif


" AutoCloseTag
" Make it so AutoCloseTag works for xml and xhtml files as well
au FileType xhtml,xml ru ftplugin/html/autoclosetag.vim
nmap <Leader>ac <Plug>ToggleAutoCloseMappings


" Fugitive
nnoremap <silent> <leader>gs :Git status<CR>
nnoremap <silent> <leader>gd :Git diff<CR>
nnoremap <silent> <leader>gb :Git blame<CR>
" Mnemonic _i_nteractive
nnoremap <silent> <leader>gi :Git add -p %<CR>

" YouCompleteMe
let g:acp_enableAtStartup = 0
" enable completion from tags
let g:ycm_collect_identifiers_from_tags_files = 1
" remap Ultisnips for compatibility for YCM
let g:UltiSnipsExpandTrigger = '<C-j>'
let g:UltiSnipsJumpForwardTrigger = '<C-j>'
let g:UltiSnipsJumpBackwardTrigger = '<C-k>'
" Enable omni completion.
" autocmd FileType css setlocal omnifunc=csscomplete#CompleteCSS
" autocmd FileType html,markdown setlocal omnifunc=htmlcomplete#CompleteTags
" autocmd FileType javascript setlocal omnifunc=javascriptcomplete#CompleteJS
" autocmd FileType javascript.jsx setlocal omnifunc=javascriptcomplete#CompleteJS
" "autocmd FileType python setlocal omnifunc=python3complete#Complete
" autocmd FileType xml setlocal omnifunc=xmlcomplete#CompleteTags
" autocmd FileType ruby setlocal omnifunc=rubycomplete#Complete
" autocmd FileType haskell setlocal omnifunc=necoghc#omnifunc

" Disable the neosnippet preview candidate window
" When enabled, there can be too much visual noise
" especially when splits are used.
set completeopt-=preview



" Wildfire
let g:wildfire_objects = {
	\ "*" : ["i'", 'i"', "i)", "i]", "i}", "ip"],
	\ "html,xml" : ["at", "it"],
	\ }

" Rust
let g:rustfmt_autosave = 1
let g:rust_clip_command = 'pbcopy'

" vim-jsx
let g:jsx_ext_required = 0

"vim-javascript
"vim-jsx
"yet another javascript vim package
"javascript library syntax
"html5
"vim-js-indent


